# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Matthew Jarvis"
email: mattjarvis@internode.on.net
description: > # this means to ignore newlines until "baseurl:"
    My name is Matthew Jarvis, I’m a developer at mVoice. I work with Java EE, Linux and Asterisk VoIP server for the most part, and dabble in various other technologies as the need arises.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username:
github_username:  peacefixation
stackoverflow_username: matt

# Build settings
markdown: kramdown
highlighter: rouge