# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Matt Jarvis"
email: 
description: > # this means to ignore newlines until "baseurl:"
    I'm a developer for a VoIP provider and do most of my work with Java and Asterisk. In my spare time I ride my mountain bike and listen to groovy music.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://peacefixation.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  peacefixation
stackoverflow_username: matt

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap