author: Martin Kleppmann
date_read: '2025-06-30'
my_rating: 4
status: read
tags:
  - computing
  - software engineering
title: Designing Data-Intensive Applications
type: book
url: https://www.goodreads.com/book/show/23463279-designing-data-intensive-applications
